// Packs assets/sounds/*.mp3 into src/sounddata.js as base64, grouped by name: "stone.dig1.mp3",
// "stone.dig2.mp3" ... become SOUNDS['stone.dig'] = [...]. Run after changing the sound files.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dir = join(root, 'assets', 'sounds');
const groups = new Map();
const files = readdirSync(dir).filter((f) => f.endsWith('.mp3'))
  .sort((a, b) => a.localeCompare(b, 'en', { numeric: true }));
for (const f of files) {
  const name = f.slice(0, -4).replace(/\d+$/, '');
  if (!groups.has(name)) groups.set(name, []);
  groups.get(name).push(readFileSync(join(dir, f)).toString('base64'));
}
let out = '// Generated by tools/pack-sounds.mjs from assets/sounds (credits in assets/sounds/CREDITS.md).\n';
out += '// Every sound is public domain (CC0). Do not edit by hand.\nexport const SOUNDS = {\n';
for (const [name, list] of groups) out += `  '${name}': [\n${list.map((b) => `    '${b}',`).join('\n')}\n  ],\n`;
out += '};\n';
writeFileSync(join(root, 'src', 'sounddata.js'), out);
console.log(`src/sounddata.js  ${groups.size} sounds, ${files.length} files, ${Math.round(out.length / 1024)} KB`);
